wandb_version: 1

copy_X:
  desc: null
  value: true
fit_intercept:
  desc: null
  value: true
n_jobs:
  desc: null
  value: null
positive:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.6
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723685710
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.17.6
      8:
      - 5
      13: linux-x86_64
    viz:
      learning_curve:
        id: wandb/learning_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: learning_curve
      feature_importances:
        id: wandb/feature_importances/v1
        historyFieldSettings:
          x-axis: _step
          key: feature_importances
test_size:
  desc: null
  value: 0.4
train_len:
  desc: null
  value: 300
test_len:
  desc: null
  value: 200
